version: '3.3'
services:
  db:
    image: postgres:10.4
    environment:
       POSTGRES_USER: test
       POSTGRES_PASSWORD: test
       POSTGRES_DB: test
       POSTGRES_HOST_AUTH_METHOD: trust
    container_name: db

  app:
    image: 'test_application/app:v1'
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    ports:
      -   "8888:8080"